### PR TITLE
moss: Add ability to disable repositories

### PR DESCRIPTION
**Pull request by tarkah**
image

### CODE REVIEW

**Review by ikeycode — COMMENTED** [review]
hold on, won't this require us overwriting a vendor shipped repo configuration in `/usr` ... ? which would be overwritten by updates..?

**Comment by tarkah** [comment]
> hold on, won't this require us overwriting a vendor shipped repo configuration in `/usr` ... ? which would be overwritten by updates..?

We only write updates to admin /etc or user config dir

**Comment by tarkah** [comment]
@ikeycode I've validated this works as expected:

- If we ship default repo / `volatile` to `/usr/share/moss/repo.d`, it shows up in `moss lr`
- User wants to "override" this / disable the repo: `moss dr volatile`
- Moss writes the overwrite to _admin_ at `/etc/moss/repo.d/volatile.yaml` w/ `active: false`
- `moss lr` shows it disabled, since it always merges admin configs _over_ vendor configs

**Review by ikeycode — APPROVED** [review]
<3

**Pull request merged**
